phpofby_website:
    resource: "@PhpOfByWebsiteBundle/Resources/config/routing.yml"
    prefix: /

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin
